# Generated by Django 4.2 on 2023-04-09 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(default='', max_length=255, verbose_name='ProductName')),
                ('ProductDesc', models.CharField(default='', max_length=255, verbose_name='ProductDesc')),
            ],
        ),
    ]
